# Generated by Django 3.2.6 on 2021-11-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imcmotivator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='autor',
            field=models.CharField(default='Arnold', max_length=50),
        ),
    ]
